# Generated by Django 3.1.1 on 2020-09-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='This is default description'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
